input {
  beats {
    port => 5044
  }
}

filter {
  if [log][file][path] {
    dissect {
      mapping => {
        "[log][file][path]" => "%{?prefix}/%{service}.log"
      }
      add_tag => ["service_extracted"]
    }
  }

  json {
    source => "message"
    target => "app"
    skip_on_invalid_json => true
  }

  if [app][service] {
    mutate {
      replace => { "service" => "%{[app][service]}" }
    }
  }

  if ![service] or [service] == "" {
    mutate {
      add_field => { "service" => "unknown" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "dating-app-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
